#!/usr/bin/expect  
# expect 接受参数实例
# file name :rauth  
# Usages : rauth username [ passworld ]  
# Description : 自动发送用户名与密码  

  
# 运行 myxrgsu -a  
if { $argc != 2 && $argc != 1 } {  
    send_user "Usage:auth username \[password\]\n"  
    send_user "\tthe default password equals 0000\n"  
    exit  
}  
  
set name [lindex $argv 0]  
if { $argc == 2 } {  
    set pass [lindex $argv 1]  
} else { set pass "0000" }  
  
spawn xrgsu  
  
# expect 开始  
expect "*user*" { send ${name}\r }  
expect "*password:" { send ${pass}\r }  
expect "*DHCP*" { send "\r" }  
expect "*auth*" { send "\r" }  
  
interact  
#EOF  
